video:
    resource: "@VideoBundle/Resources/config/routing.yml"
    prefix:   /

photo:
    resource: "@PhotoBundle/Resources/config/routing.yml"
    prefix:   /

biographie:
    resource: "@BiographieBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

discographie:
    resource: "@DiscographieBundle/Resources/config/routing.yml"
    prefix:   /Discographie
