homepage:
    pattern:  /home
    defaults: { _controller: MainBundle:Default:index }

Discographie:
    pattern:  /Discographie
    defaults: { _controller: DiscographieBundle:Default:Discographie }

Biographie:
    pattern:  /Biographie
    defaults: { _controller: BiographieBundle:Default:Biographie }

apropos:
    pattern:  /Compagnie/A-Propos
    defaults: { _controller: MainBundle:Compagnie:apropos }

suggestion:
    pattern:  /Compagnie/suggestion
    defaults: { _controller: MainBundle:Compagnie:suggestion }
    
contact:
    pattern:  /Compagnie/contact
    defaults: { _controller: MainBundle:Compagnie:contact }

Videos:
    pattern:  /Videos
    defaults: { _controller: VideosBundle:Default:Video }
    
Photos:
    pattern:  /Photos
    defaults: { _controller: PhotoBundle:Default:Photo }
    