<?php

namespace Aki\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CompagnieController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Aki\MainBundle\Controller\CompagnieController();
        return $instance;
    }
}
