parameters:
#    biographie.example.class: Aki\BiographieBundle\Example

services:
#    biographie.example:
#        class: %biographie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
